### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by dancb10** [scylladb/scylla-cdc-source-connector#59]
```
2024-12-04 20:21:59,479 ERROR Failed to discover Converter in /opt/kafka/plugins/scylladb: Unable to instantiate CloudEventsConverter: Failed to statically initialize plugin class (org.apache.kafka.connect.runtime.isolation.ReflectionScanner) [main]
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.apache.kafka.connect.runtime.isolation.ReflectionScanner.versionFor(ReflectionScanner.java:73)
	at org.apache.kafka.connect.runtime.isolation.ReflectionScanner.getPluginDesc(ReflectionScanner.java:136)
	at org.apache.kafka.connect.runtime.isolation.ReflectionScanner.scanPlugins(ReflectionScanner.java:89)
	at org.apache.kafka.connect.runtime.isolation.PluginScanner.scanUrlsAndAddPlugins(PluginScanner.java:79)
	at org.apache.kafka.connect.runtime.isolation.PluginScanner.discoverPlugins(PluginScanner.java:67)
	at org.apache.kafka.connect.runtime.isolation.Plugins.initLoaders(Plugins.java:91)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:75)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:64)
	at org.apache.kafka.connect.cli.AbstractConnectCli.startConnect(AbstractConnectCli.java:121)
	at org.apache.kafka.connect.cli.AbstractConnectCli.run(AbstractConnectCli.java:94)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:113)
Caused by: org.apache.kafka.connect.errors.DataException
	at io.debezium.converters.CloudEventsConverter.<clinit>(CloudEventsConverter.java:99)
	... 16 more

2024-12-04 20:21:59,564 INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/kafka/plugins/scylladb/} (org.apache.kafka.connect.runtime.isolation.PluginScanner) [main]
2024-12-04 20:21:59,564 INFO Loading plugin from: /opt/kafka/plugins/postgres (org.apache.kafka.connect.runtime.isolation.PluginScanner) [main]
2024-12-04 20:21:59,568 INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/kafka/plugins/postgres/} (org.apache.kafka.connect.runtime.isolation.PluginScanner) [main]
2024-12-04 20:21:59,568 INFO Loading plugin from: classpath (org.apache.kafka.connect.runtime.isolation.PluginScanner) [main]
2024-12-04 20:22:05,932 INFO Registered loader: jdk.internal.loader.ClassLoaders$AppClassLoader@2b2fa4f7 (org.apache.kafka.connect.runtime.isolation.PluginScanner) [main]
2024-12-04 20:22:05,932 INFO Scanning plugins with ReflectionScanner took 11356 ms (org.apache.kafka.connect.runtime.isolation.PluginScanner) [main]
2024-12-04 20:22:05,936 WARN One or more plugins are missing ServiceLoader manifests may not be usable with plugin.discovery=service_load: [
file:/opt/kafka/plugins/scylladb/	com.scylladb.cdc.debezium.connector.ScyllaConnector	source	1.2.2
file:/opt/kafka/plugins/scylladb/	com.scylladb.cdc.debezium.connector.transforms.ScyllaExtractNewRecordState	transformation	undefined
file:/opt/kafka/plugins/scylladb/	com.scylladb.cdc.debezium.connector.transforms.ScyllaFlattenColumns	transformation	undefined
file:/opt/kafka/plugins/scylladb/	io.debezium.converters.ByteBufferConverter	converter	undefined
file:/opt/kafka/plugins/scylladb/	io.debezium.converters.ByteBufferConverter	header_converter	undefined
file:/opt/kafka/plugins/scylladb/	io.debezium.transforms.ByLogicalTableRouter	transformation	undefined
file:/opt/kafka/plugins/scylladb/	io.debezium.transforms.ExtractNewRecordState	transformation	undefined
file:/opt/kafka/plugins/scylladb/	io.debezium.transforms.outbox.EventRouter	transformation	undefined
file:/opt/kafka/plugins/scylladb/	io.debezium.transforms.tracing.ActivateTracingSpan	transformation	undefined
]
Read the documentation at https://kafka.apache.org/documentation.html#connect_plugindiscovery for instructions on migrating your plugins to take advantage of the performance improvements of service_load mode. To silence this warning, set plugin.discovery=only_scan in the worker config. (org.apache.kafka.connect.runtime.isolation.Plugins) [main]
```

With kafka-3.8.0, is there a kafka compatibility issue?

**Comment by mykaul** [comment]
CC @roydahan (we should have a matrix of Kafka versions tested in CI, I reckon).
